bulldog/urls.py
"""bulldog URL Configuration

"""
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('services.urls'))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

services/urls.py
from django.urls import path

from . import views

app_name = 'services'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index_view'),
    path('authenticate-user/', views.AuthView.as_view(), name='auth_view'),
    path('user/new/', views.CreateUserView.as_view(), name='create_view'),
    path('dashboard/', views.DashboardView.as_view(), name='dashboard_view'),
    path('user/verify/', views.VerifyCodeView.as_view(), name='verify_view'),
    path('user/logout/', views.LogoutView.as_view(), name='logout_view'),
    path('user/verify-deposit/', views.VerifyDepositView.as_view(),
         name='verify_deposit_view'),
    path('user/withdraw/', views.WithdrawView.as_view(), name='withdraw_view'),
    path('user/history/', views.HistoryView.as_view(), name='history_view'),
    path('faq/', views.FAQView.as_view(), name='faq_view'),
    path('about-us/', views.FAQView.as_view(), name='contact_view'),
    path('contact-us/', views.ContactView.as_view(), name='contact_view'),
    path('user/profile/', views.ProfileView.as_view(), name='profile_view'),
    path('user/wallet/', views.WalletView.as_view(), name='wallet_view'),
    path('user/upload-id/', views.UploadIDView.as_view(), name='upload_id_view'),


]

services/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models


# Deposit
class Deposit(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='deposits', on_delete=models.CASCADE)
    address = models.CharField(max_length=48)
    amount = models.DecimalField(max_digits=8, decimal_places=4)
    asset = models.CharField(max_length=48, choices=(
        ('Bitcoin', 'Bitcoin'),
        ('Ethereum', 'Ethereum'),
        ('Dogecoin', 'Dogecoin'),
        ('Litecoin', 'Litecoin')
    ))
    date = models.DateField()
    time = models.TimeField()
    has_been_verified = models.BooleanField(default=False)
    status = models.CharField(max_length=48, default='pending', choices=(
        ('pending', 'Pending'),
        ('declined', 'Declined'),
        ('verified', 'Verified'),
        ('credited', 'Credited')
    ))
    processed = models.BooleanField(default=False, editable=False)
    txref = models.UUIDField(default=uuid.uuid4, unique=True)
    date_created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return "Deposit {0}".format(self.id)


# Withdrawal
class Withdrawal(models.Model):
    user = models.ForeignKey(
        get_user_model(), related_name='withdrawals', on_delete=models.CASCADE)
    address = models.CharField(max_length=48)
    amount = models.DecimalField(max_digits=8, decimal_places=2)
    asset = models.CharField(max_length=48, choices=(
        ('Bitcoin', 'Bitcoin'),
        ('Ethereum', 'Ethereum'),
        ('Dogecoin', 'Dogecoin'),
        ('Litecoin', 'Litecoin')
    ))
    date = models.DateField(auto_now_add=True)
    time = models.TimeField(auto_now_add=True)
    status = models.CharField(max_length=48, default='pending', choices=(
        ('pending', 'Pending'),
        ('declined', 'Declined'),
        ('paid', 'Paid')
    ))
    has_been_settled = models.BooleanField(default=False)
    processed = models.BooleanField(default=False, editable=False)
    txref = models.UUIDField(default=uuid.uuid4, unique=True)
    date_created = models.DateTimeField(auto_now_add=True, editable=False)

    def __str__(self):
        return "Withdrawal {0}".format(self.id)


def get_btc_addr():
    uid = uuid.uuid4().hex
    if UserWallet.objects.filter(btc_address=uid).exists():
        return get_btc_addr()
    return uid


# User Wallet


class UserWallet(models.Model):
    user = models.OneToOneField(
        get_user_model(), related_name='wallet', on_delete=models.CASCADE)
    balance = models.PositiveBigIntegerField(default=0)
    btc_balance = models.DecimalField(
        max_digits=20, decimal_places=12, default=0)
    btc_address = models.CharField(
        max_length=48, default=get_btc_addr, unique=True)
    eth_balance = models.DecimalField(
        max_digits=20, decimal_places=12, default=0)
    eth_address = models.CharField(
        max_length=48, default=get_btc_addr, unique=True)
    doge_balance = models.DecimalField(
        max_digits=20, decimal_places=12, default=0)
    doge_address = models.CharField(
        max_length=48, default=get_btc_addr, unique=True)
    lite_balance = models.DecimalField(
        max_digits=20, decimal_places=12, default=0)
    lite_address = models.CharField(
        max_length=48, default=get_btc_addr, unique=True)

    def decrease(self, amt):
        if amt > self.balance:
            return False
        self.balance -= amt
        self.save()
        return True

    def balance_string(self):
        return self.balance

    def increase(self, amt):
        self.balance += amt
        self.save()

    def __str__(self):
        return "{0}'s wallet".format(self.user.get_full_name())

services/forms.py
from django import forms


class VerifyForm(forms.Form):
    asset = forms.CharField(max_length=35, required=True, min_length=4)
    address = forms.CharField(max_length=48, required=True, min_length=32)
    amount = forms.DecimalField(
        max_digits=20, min_value=0.0000000000000001, decimal_places=16, required=True)
    time = forms.TimeField(required=True)
    date = forms.DateField(required=True)


class WithdrawForm(forms.Form):
    asset = forms.CharField(max_length=35, required=True, min_length=4)
    address = forms.CharField(max_length=48, required=True, min_length=32)
    amount = forms.DecimalField(
        max_digits=16, min_value=10, decimal_places=4, required=True)


class SignInForm(forms.Form):
    email = forms.EmailField(max_length=255, required=True)
    password = forms.CharField(max_length=25, min_length=8, required=True)


class SignUpForm(forms.Form):
    firstname = forms.CharField(max_length=35, min_length=3, required=True)
    lastname = forms.CharField(max_length=35, min_length=3, required=True)
    email = forms.EmailField(max_length=255, required=True)
    dob = forms.DateField(required=True)
    password1 = forms.CharField(max_length=25, min_length=8, required=True)
    password2 = forms.CharField(max_length=25, min_length=8, required=True)

services/views.py
import uuid

from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import mail
from django.core.mail import send_mail
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views import View
from users.models import User, UserData, VerificationCode

from .forms import *
from .mails import mail_message
from .models import Deposit, UserWallet, Withdrawal


def generate_unique_code():
    code1 = uuid.uuid4().clock_seq
    code2 = uuid.uuid4().clock_seq
    code = str(code1) + str(code2)
    code = code[:7]
    if VerificationCode.objects.filter(code=code).count() > 1:
        return generate_unique_code()

    return code

    # Index View


class UploadIDView(LoginRequiredMixin, View):
    def post(self, request):
        id_file = request.FILES.get('ID', None)
        if id_file is None:
            context = {
                'message': "An error occured while uploading your ID.Please check and try again.", 'color': 'red'}
            return render(request, 'services/profile.html', context)

        request.user.has_uploaded_id = True
        request.user.save()
        context = {
            'message': "Your ID has been successfully uploaded!", 'color': 'green'}
        return render(request, 'services/dashboard.html', context)


class IndexView(View):
    def get(self, request):
        # if request.user.is_authenticated:
        #     return redirect('/dashboard/')
        context = {'formB': 'hidden', 'formA': 'block'}
        return render(request, 'services/index.html', context)


class ProfileView(LoginRequiredMixin, View):
    def get(self, request):
        context = {'bitcoinAddress': '3L3LnvfKMTVZcZJtTR7eLdoMzh4g8n1QyS', 'ethereumAddress': '0x9cbd14f198d4addad022beb882ad069ec2163a3c',
                   'dogecoinAddress': 'D8Kr7nbfG9ykqes5miiq78mfiF6Hf2XnmD', 'litecoinAddress': 'LT4o4VedSQrnCFQus8oPJWMRe2xnNQonUq'}
        return render(request, 'services/profile.html', context)


class WalletView(LoginRequiredMixin, View):
    def get(self, request):
        context = {'bitcoinAddress': '3L3LnvfKMTVZcZJtTR7eLdoMzh4g8n1QyS', 'ethereumAddress': '0x9cbd14f198d4addad022beb882ad069ec2163a3c',
                   'dogecoinAddress': 'D8Kr7nbfG9ykqes5miiq78mfiF6Hf2XnmD', 'litecoinAddress': 'LT4o4VedSQrnCFQus8oPJWMRe2xnNQonUq'}
        return render(request, 'services/wallet.html', context)


class FAQView(View):
    def get(self, request):
        context = {}
        return render(request, 'services/faq.html', context)


class ContactView(View):
    def get(self, request):
        context = {}
        return render(request, 'services/contact.html', context)


# Tx History
class HistoryView(LoginRequiredMixin,  View):
    login_url = '/authenticate-user/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        deposits = Deposit.objects.order_by('-time').order_by('-date').all()
        withdrawals = Withdrawal.objects.order_by('-time').order_by(
            '-date').all()
        context = {'withdrawals': withdrawals, 'deposits': deposits, 'bitcoinAddress': '3L3LnvfKMTVZcZJtTR7eLdoMzh4g8n1QyS', 'ethereumAddress': '0x9cbd14f198d4addad022beb882ad069ec2163a3c',
                   'dogecoinAddress': 'D8Kr7nbfG9ykqes5miiq78mfiF6Hf2XnmD', 'litecoinAddress': 'LT4o4VedSQrnCFQus8oPJWMRe2xnNQonUq'}
        return render(request, 'services/history.html', context)


# Verify Deposit View
class VerifyDepositView(LoginRequiredMixin, View):
    login_url = '/authenticate-user/'
    redirect_field_name = 'redirect_to'

    def post(self, request):
        form = VerifyForm(request.POST)
        if form.is_valid():

            deposit = Deposit.objects.create(
                **form.cleaned_data, user=request.user)
            deposit.save()
            pass
            context = {
                'message': 'Your request has been placed, you will receive a confirmation email immediately your claim is confirmed.', 'color': 'green'}
            return render(request, 'services/dashboard.html', context)
        else:
            errors = ''
            for field in form:
                if not(field.errors):
                    continue
                error = '<span>{0} '.format(
                    field.label)
                for ferror in field.errors:
                    error += '<br> <span class = "text-base">  {0} </span>'.format(
                        ferror)
                errors += '<br>{0} </span'.format(error)

            context = {'message': errors, 'color': 'red'}
            return render(request, 'services/dashboard.html', context)


# Withdraw View
class WithdrawView(LoginRequiredMixin, View):
    login_url = '/authenticate-user/'
    redirect_field_name = 'redirect_to'

    def post(self, request):
        form = WithdrawForm(request.POST)
        if form.is_valid():
            if form.cleaned_data['amount'] >= request.user.wallet.balance:
                context = {
                    'message': "You don't have sufficient balance for this transaction, please fund your account and try again later", 'color': 'red'}
                return render(request, 'services/dashboard.html', context)

            withdrawal = Withdrawal.objects.create(
                **form.cleaned_data, user=request.user)
            withdrawal.save()

            context = {
                'message': 'Your withdrawal request has been placed, you will receive a confirmation email soon. You can monitor updates in transaction history', 'color': 'green'}
            return render(request, 'services/dashboard.html', context)
        else:
            errors = ''
            for field in form:
                if not(field.errors):
                    continue
                error = '<span>{0} '.format(
                    field.label)
                for ferror in field.errors:
                    error += '<br> <span class = "text-base">  {0} </span>'.format(
                        ferror)
                errors += '<br>{0} </span'.format(error)
            context = {'message': errors, 'color': 'red'}
            return render(request, 'services/dashboard.html', context)


# dashboard View
class DashboardView(LoginRequiredMixin, View):
    login_url = '/authenticate-user/'
    redirect_field_name = 'redirect_to'

    def get(self, request):
        context = {'bitcoinAddress': '3L3LnvfKMTVZcZJtTR7eLdoMzh4g8n1QyS', 'ethereumAddress': '0x9cbd14f198d4addad022beb882ad069ec2163a3c',
                   'dogecoinAddress': 'D8Kr7nbfG9ykqes5miiq78mfiF6Hf2XnmD', 'litecoinAddress': 'LT4o4VedSQrnCFQus8oPJWMRe2xnNQonUq'}
        return render(request, 'services/dashboard.html', context)


# Verify Code
class VerifyCodeView(View):

    def post(self, request):
        code = request.POST.get('code', '')
        # print("Code is :", code)

        if code == '':
            context = {'message': 'The field is empty', 'color': '#E49B0F'}
            return render(request, 'services/confirmemail.html', context)

        code_object = None
        try:
            code_object = VerificationCode.objects.get(code=code)
        except VerificationCode.DoesNotExist:
            context = {
                'message': 'Incorrect code, please check and try again.', 'color': 'red'}
            return render(request, 'services/confirmemail.html', context)

        saved_user = request.session.get('temporal_saved_data', None)
        if saved_user is None:
            return redirect('/')

        if code_object.email == saved_user['email']:
            fn = saved_user['firstname']
            ln = saved_user['lastname']
            dob = saved_user['dob']
            email = saved_user['email']
            password2 = saved_user['password2']

            user_data = UserData.objects.create(dob=dob)
            user_data.save()
            user = User.objects.create(
                firstname=fn, lastname=ln, email=email, data=user_data)
            user.save()
            user.set_password(password2)
            # print(user.password)
            user.save()
            request.session['temporal_saved_data'] = None
            request.session.flush()

            code_object.delete()

            return redirect(reverse("services:auth_view"))

        else:
            context = {
                'message': 'Incorrect code, please check and try again.', 'color': '#E49B0F'}
            return render(request, 'services/confirmemail.html', context)


# Logout View
class LogoutView(View):
    def get(self, request):
        context = {'message': 'You have been logged out.',
                   'formB': 'hidden', 'formA': 'block'}
        logout(request)
        request.session.flush()
        return render(request, 'services/index.html', context)


# CreateUser View
class CreateUserView(View):
    def get(self, request):
        if request.user.is_authenticated:
            return redirect('/dashboard/')
        context = {'formB': 'block', 'formA': 'hidden', }
        return render(request, 'services/auth.html', context)

    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():

            firstname = form.cleaned_data['firstname']
            email = form.cleaned_data['email']
            password1 = form.cleaned_data['password1']
            password2 = form.cleaned_data['password2']

            if User.objects.filter(email=email).exists():
                context = {'message': '[ <small>' + email + ' </small>] <br> This email has been taken',
                           'formA': 'hidden', 'formB': 'block'}
                return render(request, 'services/auth.html', context)

            if(password1 and password2) and (password1 == password2):

                saved_user_data = form.cleaned_data.copy()
                saved_user_data['dob'] = request.POST['dob']
                request.session['temporal_saved_data'] = saved_user_data

                # send the code here

services/templates/services/auth.html
{% extends 'services/base.html' %}

services/templates/services/confirmemail.html
{% extends 'services/base.html' %}

{% block title %}
Confirm | usbeenance
{% endblock %}


{% block main %}


<!-- The Email Confirmation  form  -->
<div id='form3'
     class='max-w-md  mx-auto md:ring-1 md:ring-gray-700 md:bg-gray-700 p-2 px-10 rounded-xl mt-12'>
    <form class=''
          method='post'
          action='{% url "services:verify_view" %}'>

        {% csrf_token %}

        <legend style='font-family:"Work Sans";'
                class='text-left text-2xl md:text-white my-5 block text-gray-700 font-bold mb-12  select-none'>
            Please enter the code we sent to your inbox to verify your email address</legend>

        <div class='m-2'>
            <label style='font-family:"Work Sans";'
                   class='text-left md:text-white text-2xl font-normal text-gray-700 my-4 block'>
                Verification Code
            </label>
            <input style='font-family:"Raleway";'
                   required
                   minlength="4"
                   class='pt-3 pr-5 pb-3 pl-5 rounded  block  w-full  outline-none text-lg text-center'
                   name='code'
                   type='text' />
        </div>


        <button class='block  mx-auto w-full  hover:bg-green-700 mt-16  my-2 bg-green-700 rounded-lg ring-2 ring-green-900 text-2xl text-white  text-center py-3 px-5 outline-none'
                type='submit'>
            Continue </button>
    </form>
</div>



{% endblock %}

services/templates/services/profile.html
{% extends 'services/dashboard.html' %}

{% block essentials %}
<!-- New chip in  -->

<div
     class='mt-6 md:max-w-4xl w-11/12 min-h-6 rounded-xl mb-6 shadow mx-auto  p-3 flex  flex-col flex-wrap content-center items-center pb-6  justify-evenly bg-gray-400'>



   <div> <i class='bi-person-circle text-9xl text-yellow-500'></i></div>
   <br>

   <div style='font-family:"Work Sans";'
        class='text-center'>
      <p class='font-bold text-3xl text-gray-600 capitalize  p-2 m-0 '>
         {{request.user.get_full_name}}</p>

      <p class='font-normal text-2xl text-gray-600   p-2 m-0 '>
         {{request.user.email}}</p>



      <div style='font-family:"Work Sans";'
           class='font-bold   text-xl text-gray-500'>
         <p class='p-2 py-4'> Status :{% if request.user.verified %}<span class='text-green-500'>
               Verified
            </span> {% elif request.user.has_uploaded_id %}<span class='text-yellow-500'> Pending
               verification
            </span>{% else %}
            <span class='text-red-500'> Unverified
            </span>
            {% endif %}

         </p>
         <p class='p-2 py-4'> Wallet balance :
            <span class='text-yellow-400'> &dollar;{{request.user.wallet.balance}}</span>
         </p>
         <br>
         <br>

         {% if  not request.user.has_uploaded_id  %}
         <button id='showVerifyAccountBox'
                 class='block p-2 max-w-md text-white bg-green-600 rounded mx-auto text-center px-4 hover:bg-green-500 capitalize'>
            Verify account </button>
         {% endif %}
      </div>


      <!-- start of pop up  -->


      <div id='verifyAccountBox'
           class=" hidden coinBox min-h-screen overflow-y-scroll  bg-gray-200 rounded-lg fixed left-0 top-0 bottom-0 right-0 p-2 px-10   right-0 z-30 mx-auto  py-5 max-w-md">

         <i onclick="this.parentElement.style.display = 'none'"
            class=' absolute top-0 ring-1 ring-gray-50 right-0 bg-gray-600 hover:bg-gray-700  text-white text-2xl px-3 bi-x'></i>


         <h4 style='font-family:"Work Sans";'
             class='text-center p-2 text-sm  font-bold text-gray-700 uppercase'> VERIFY YOUR ACCOUNT
         </h4>

         <form class=''
               enctype="multipart/form-data"
               method='post'
               action='{% url "services:upload_id_view" %}'>

            {% csrf_token %}

            <legend style='font-family:"Work Sans";'
                    class='md:text-left text-center text-2xl md:text-gray-700 my-5 block text-gray-700 font-bold mb-12 capitalize select-none'>
               <i class='bi-person-check-fill'></i>
               Upload an ID card to verify your account
            </legend>

            <div class='m-2 ring-2 ring-gray-700 ring-opacity-80 rounded py-6'>
               <label style='font-family:"Work Sans";'
                      class='text-center md:text-white text-2xl font-bold text-gray-700 my-4 block'>
                  ID / National Passport
               </label>
               <input type='file'
                      name='ID'
                      required
                      class='ring-2 ring-gray-700 rounded w-5/6  block mx-auto'>

            </div>



            <div>
               <p style="font-family:Raleway"
                  class='toggleForms  text-gray-700 md:text-white pt-5 text-base text-center '>
                  You are to upload a clear picture of your ID above. Verification will be done and
                  your account will be verified provided the ID is authenticated.
               </p>
               <br>

            </div>

            <button class='block  mx-auto w-full  hover:bg-green-700 mt-4  my-2 bg-green-700 rounded-lg ring-2 ring-green-900 text-2xl text-white  text-center py-3 px-5 outline-none'
                    type='submit'>
               Proceed </button>
         </form>


         <br>







      </div>

      <!-- end of pop up  -->

   </div>




</div>

{% endblock essentials %}

services/templates/services/verifymailtemplate.html
<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible"
              content="IE=edge">
        <meta name="viewport"
              content="width=device-width, initial-scale=1.0">
        <title>Document</title>
    </head>

    <body style='background-color:azure;padding:10px;'>

        <p
           style='margin:auto;padding:10px;font-weight:bold;text-align: center; text-transform:uppercase;'>
            BEENANCE </p>

        <br>

        <p class=''
           style='color:black;opacity:0.85;font-size: 100%;text-align:left;font-weight:700;margin:auto;margin-top:15px;margin-bottom: 15px;padding:10px;'>
            Hello! Your email
            address was used to
            create an acccount on our platform,
            please verify
            your account using the code below</p>


        <br>
        <p style="margin:auto;font-size:130%;font-weight: bold;text-align: center;padding:20px;">
        </p>

        <br>
        <br>
        <p style='font-size:85%;text-align:left;'> Best regards, The Beenance team.</p>




    </body>

</html>

services/templates/services/wallet.html
{% extends 'services/dashboard.html' %}

{% block essentials %}

<div class='my-6'>
   <p class='text-3xl capitalize p-4 text-center font-bold text-gray-100'> Total Value
   </p>
   <b
      class='text-5xl block font-bold p-2 text-center text-gray-900'>&dollar;{{request.user.wallet.balance}}</b>


   <br>
   <br>

   <div class='flex flex-row space-x-12 justify-around space-x-4 content-center '>
      <button id='showBitcoin'
              style='font-family:"Inter"'
              class='flex-initial w-1/4 p-2 rounded py-4 flex-grow-0 flex-shrink-1 text-gray-900 font-bold bg-yellow-500 hover:bg-yellow-400 '>
         Deposit
      </button>
      <button id='showWithdrawForm'
              style='font-family:"Inter"'
              class='flex-initial w-1/4 p-2 rounded font-bold py-4 flex-grow-0 flex-shrink-1 text-gray-900 bg-yellow-500 hover:bg-yellow-400 '>
         Withdraw
      </button>

   </div>

   <br>
   <br>
   <br>


   <!-- Coins  -->
   <div class='flex flex-col mb-8 space-y-8 justify-center content-center'>

      <div class='mx-2'>
         <div style='font-family:"Inter"'
              class='flex space-y-4 md:space-y-0 m-4 pt-4 md:m-0 ring-1 rounded-lg ring-gray-800 md:ring-0 flex-col  md:flex-row  space-x-8 justify-center md:justify-evenly content-center'>
            <img src='/static/services/m_bit.jpeg'
                 height='50'
                 width='50'
                 class='self-center rounded-full'
                 alt='coin'>
            <span class='font-bold self-center text-gray-800 text-2xl'> Bitcoin </span>
            <span style='font-family:"consolas"'
                  class='flex-initial select-none self-center font-bold text-base  p-1 px-2 rounded  flex-grow-1 flex-shrink-1 text-gray-900 bg-yellow-500 '>
               <i title='Copy address'
                  id='copyBitcoinWallet'
                  class='bi-clipboard cursor-pointer hover:text-yellow-900 text-yellow-200 text-2xl '></i>&nbsp;&nbsp;
               {{request.user.wallet.btc_address | truncatechars:20}} </span>
            <span class='font-bold self-center  text-2xl text-gray-800'>
               {{request.user.wallet.btc_balance}}</span>
         </div>
      </div>




      <div class='mx-2'>
         <div style='font-family:"Inter"'
              class='flex space-y-4 md:space-y-0 m-4 pt-4 md:m-0 ring-1 rounded-lg ring-gray-800 md:ring-0 flex-col  md:flex-row  space-x-8 justify-center md:justify-evenly content-center'>
            <img src='/static/services/m_eth.jpeg'
                 height='50'
                 width='50'
                 class='self-center rounded-full'
                 alt='coin'>
            <span class='font-bold self-center text-gray-800 text-2xl'> Ethereum </span>
            <span style='font-family:"consolas"'
                  class='flex-initial select-none self-center font-bold text-base  p-1 px-2 rounded  flex-grow-1 flex-shrink-1 text-gray-900 bg-yellow-500 '>
               <i title='Copy address'
                  id='copyEthereumWallet'
                  class='bi-clipboard cursor-pointer hover:text-yellow-900 text-yellow-200 text-2xl '></i>&nbsp;&nbsp;
               {{request.user.wallet.eth_address | truncatechars:20}} </span>
            <span class='font-bold self-center  text-2xl text-gray-800'>
               {{request.user.wallet.eth_balance}}</span>
         </div>
      </div>






      <div class='mx-2'>
         <div style='font-family:"Inter"'
              class='flex space-y-4 md:space-y-0 m-4 pt-4 md:m-0 ring-1 rounded-lg ring-gray-800 md:ring-0 flex-col  md:flex-row  space-x-8 justify-center md:justify-evenly content-center'>
            <img src='/static/services/dogecoin4.png'
                 height='50'
                 width='50'
                 class='self-center rounded-full'
                 alt='coin'>
            <span class='font-bold self-center text-gray-800 text-2xl'> Dogecoin </span>
            <span style='font-family:"consolas"'
                  class='flex-initial select-none self-center font-bold text-base  p-1 px-2 rounded  flex-grow-1 flex-shrink-1 text-gray-900 bg-yellow-500 '>
               <i title='Copy address'
                  id='copyDogecoinWallet'
                  class='bi-clipboard cursor-pointer hover:text-yellow-900 text-yellow-200 text-2xl '></i>&nbsp;&nbsp;
               {{request.user.wallet.doge_address | truncatechars:20}} </span>
            <span class='font-bold self-center  text-2xl text-gray-800'>
               {{request.user.wallet.doge_balance}}</span>
         </div>
      </div>



      <div class='mx-2'>
         <div style='font-family:"Inter"'
              class='flex space-y-4 md:space-y-0 m-4 pt-4 md:m-0 ring-1 rounded-lg ring-gray-800 md:ring-0 flex-col  md:flex-row  space-x-8 justify-center md:justify-evenly content-center'>
            <img src='/static/services/m_lite.jpeg'
                 height='50'
                 width='50'
                 class='self-center rounded-full'
                 alt='coin'>
            <span class='font-bold self-center text-gray-800 text-2xl'> Litecoin </span>
            <span style='font-family:"consolas"'
                  class='flex-initial select-none self-center font-bold text-base  p-1 px-2 rounded  flex-grow-1 flex-shrink-1 text-gray-900 bg-yellow-500 '>
               <i title='Copy address'
                  id='copyLitecoinWallet'
                  class='bi-clipboard cursor-pointer hover:text-yellow-900 text-yellow-200 text-2xl '></i>
               &nbsp;&nbsp;
               {{request.user.wallet.lite_address | truncatechars:20}} </span>
            <span class='font-bold self-center  text-2xl text-gray-800'>
               {{request.user.wallet.lite_balance}}</span>
         </div>
      </div>


   </div>

   <!-- coins end  -->

</div>


{% endblock essentials %}